
//communication
#define TX PB10
#define RX PB11

#define TURNTABLE_TRAVEL_ANGLE 0
#define BASE_ARM_TRAVEL_ANGLE 0
#define FORE_ARM_TRAVEL_ANGLE 0
#define WRIST_TRAVEL_ANGLE 0

#define TURNTABLE_ASCENT_ANGLE 0
#define BASE_ARM_ASCENT_ANGLE 0
#define FORE_ARM_ASCENT_ANGLE 0
#define WRIST_ASCENT_ANGLE 0

#define TURNTABLE_SEARCH_LEFT 0 
#define TURNTABLE_SEARCH_RIGHT 0
#define BASE_ARM_SEARCH_ANGLE 0
#define FORE_ARM_SEARCH_ANGLE 0
#define WRIST_SEARCH_ANGLE 0

#define TURNTABLE_SEARCH_ARC 0
#define TURNTABLE_STEP_RESOLUTION 0

#define LEFT_SIDE  0
#define RIGHT_SIDE 1

#define POST_1_HEIGHT 0
#define POST_2_HEIGHT 0
#define POST_3_HEIGHT 0
#define POST_4_HEIGHT 0
#define POST_5_HEIGHT 0
#define POST_6_HEIGHT 0

#define GAUNTLET_POS_1_X 0
#define GAUNTLET_POS_1_Y 0
#define GAUNTLET_POS_1_Z 0

#define GAUNTLET_POS_2_X 0
#define GAUNTLET_POS_2_Y 0
#define GAUNTLET_POS_2_Z 0

#define GAUNTLET_POS_3_X 0
#define GAUNTLET_POS_3_Y 0
#define GAUNTLET_POS_3_Z 0

#define GAUNTLET_POS_4_X 0
#define GAUNTLET_POS_4_Y 0
#define GAUNTLET_POS_4_Z 0

#define GAUNTLET_POS_5_X 0
#define GAUNTLET_POS_5_Y 0
#define GAUNTLET_POS_5_Z 0

#define GAUNTLET_POS_6_X 0
#define GAUNTLET_POS_6_Y 0
#define GAUNTLET_POS_6_Z 0

#define Z_PULLUP_DISTANCE 0

#define VERTICAL_STEP_RESOLUTION 0

#define L1 20
#define L2 20
#define L3 5
#define RAD_DEG 180.0/3.1415926535
#define DEG_RAD 3.1415925635/180.0

#define UNREACHABLE_ERROR 0

#define EXTENSION_LENGTH 0